create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  liked boolean not null,
  age_bucket text not null check (age_bucket in ('14-','14','15','16','17','18','19','20','21','22','23+')),
  gender text not null check (gender in ('Мужчина','Женщина')),
  created_at timestamptz not null default now()
);

alter table public.votes enable row level security;

drop policy if exists "public can read votes" on public.votes;
create policy "public can read votes"
on public.votes for select
to anon
using (true);

drop policy if exists "public can insert votes" on public.votes;
create policy "public can insert votes"
on public.votes for insert
to anon
with check (true);
